## 0. 설치

In [ ]:
!pip install polars

Requirement already satisfied: polars in /usr/local/lib/python3.11/dist-packages (1.21.0)

## 1. 데이터 읽기

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
## 파일 데이터 읽기(eager mode)
import polars as pl
df = pl.read_csv("/content/drive/MyDrive/BigData/polars/emp.csv")

df.head()

shape: (5, 8)
┌────────────┬────────┬────────────┬────────────┬────────┬────────┬────────────────────┬───────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login ┆ Salary ┆ Bonus  ┆ Senior Management  ┆ Team      │
│ ---        ┆ ---    ┆ ---        ┆ Time       ┆ ---    ┆ ---    ┆ ---                ┆ ---       │
│ str        ┆ str    ┆ str        ┆ ---        ┆ i64    ┆ f64    ┆ bool               ┆ str       │
│            ┆        ┆            ┆ str        ┆        ┆        ┆                    ┆           │
╞════════════╪════════╪════════════╪════════════╪════════╪════════╪════════════════════╪═══════════╡
│ Douglas    ┆ Male   ┆ 8/6/1993   ┆ 12:42 PM   ┆ 97308  ┆ 6.945  ┆ true               ┆ Marketing │
│ Thomas     ┆ Male   ┆ 3/31/1996  ┆ 6:53 AM    ┆ 61933  ┆ 4.17   ┆ true               ┆ null      │
│ Maria      ┆ Female ┆ 4/23/1993  ┆ 11:17 AM   ┆ 130590 ┆ 11.858 ┆ false              ┆ Finance   │
│ Jerry      ┆ Male   ┆ 3/4/2005   ┆ 1:00 PM    ┆ 138705 ┆ 9.34   ┆ true               ┆ Finance   │
│ Larry      ┆ Male   ┆ 1/24/1998  ┆ 4:47 PM    ┆ 101004 ┆ 1.389  ┆ true               ┆ Client    │
│            ┆        ┆            ┆            ┆        ┆        ┆                    ┆ Services  │
└────────────┴────────┴────────────┴────────────┴────────┴────────┴────────────────────┴───────────┘

In [3]:
## 스키마 탐색

df.schema

Schema([('First Name', String),
        ('Gender', String),
        ('Start Date', String),
        ('Last Login Time', String),
        ('Salary', Int64),
        ('Bonus', Float64),
        ('Senior Management', Boolean),
        ('Team', String)])

In [4]:
## 컬럼 확인

df.columns

['First Name',
 'Gender',
 'Start Date',
 'Last Login Time',
 'Salary',
 'Bonus',
 'Senior Management',
 'Team']

In [5]:
## 컬럼 수치 정보 확인

df.describe()

shape: (9, 9)
┌────────────┬────────┬────────┬────────────┬───┬────────────┬───────────┬────────────┬────────────┐
│ statistic  ┆ First  ┆ Gender ┆ Start Date ┆ … ┆ Salary     ┆ Bonus     ┆ Senior     ┆ Team       │
│ ---        ┆ Name   ┆ ---    ┆ ---        ┆   ┆ ---        ┆ ---       ┆ Management ┆ ---        │
│ str        ┆ ---    ┆ str    ┆ str        ┆   ┆ f64        ┆ f64       ┆ ---        ┆ str        │
│            ┆ str    ┆        ┆            ┆   ┆            ┆           ┆ f64        ┆            │
╞════════════╪════════╪════════╪════════════╪═══╪════════════╪═══════════╪════════════╪════════════╡
│ count      ┆ 933    ┆ 855    ┆ 1000       ┆ … ┆ 1000.0     ┆ 1000.0    ┆ 933.0      ┆ 957        │
│ null_count ┆ 67     ┆ 145    ┆ 0          ┆ … ┆ 0.0        ┆ 0.0       ┆ 67.0       ┆ 43         │
│ mean       ┆ null   ┆ null   ┆ null       ┆ … ┆ 90662.181  ┆ 10.207555 ┆ 0.501608   ┆ null       │
│ std        ┆ null   ┆ null   ┆ null       ┆ … ┆ 32923.6933 ┆ 5.528481  ┆ null       ┆ null       │
│            ┆        ┆        ┆            ┆   ┆ 42         ┆           ┆            ┆            │
│ min        ┆ Aaron  ┆ Female ┆ 1/1/2014   ┆ … ┆ 35013.0    ┆ 1.015     ┆ 0.0        ┆ Business   │
│            ┆        ┆        ┆            ┆   ┆            ┆           ┆            ┆ Developmen │
│            ┆        ┆        ┆            ┆   ┆            ┆           ┆            ┆ t          │
│ 25%        ┆ null   ┆ null   ┆ null       ┆ … ┆ 62666.0    ┆ 5.413     ┆ null       ┆ null       │
│ 50%        ┆ null   ┆ null   ┆ null       ┆ … ┆ 90429.0    ┆ 9.849     ┆ null       ┆ null       │
│ 75%        ┆ null   ┆ null   ┆ null       ┆ … ┆ 118736.0   ┆ 14.837    ┆ null       ┆ null       │
│ max        ┆ Willie ┆ Male   ┆ 9/9/2006   ┆ … ┆ 149908.0   ┆ 19.944    ┆ 1.0        ┆ Sales      │
└────────────┴────────┴────────┴────────────┴───┴────────────┴───────────┴────────────┴────────────┘

## 2. 컬럼 다루기

In [6]:
## 인덱스 컬럼 생성

df1 = df.with_row_index()
df1.head()

shape: (5, 9)
┌───────┬────────────┬────────┬────────────┬───┬────────┬────────┬────────────┬─────────────────┐
│ index ┆ First Name ┆ Gender ┆ Start Date ┆ … ┆ Salary ┆ Bonus  ┆ Senior     ┆ Team            │
│ ---   ┆ ---        ┆ ---    ┆ ---        ┆   ┆ ---    ┆ ---    ┆ Management ┆ ---             │
│ u32   ┆ str        ┆ str    ┆ str        ┆   ┆ i64    ┆ f64    ┆ ---        ┆ str             │
│       ┆            ┆        ┆            ┆   ┆        ┆        ┆ bool       ┆                 │
╞═══════╪════════════╪════════╪════════════╪═══╪════════╪════════╪════════════╪═════════════════╡
│ 0     ┆ Douglas    ┆ Male   ┆ 8/6/1993   ┆ … ┆ 97308  ┆ 6.945  ┆ true       ┆ Marketing       │
│ 1     ┆ Thomas     ┆ Male   ┆ 3/31/1996  ┆ … ┆ 61933  ┆ 4.17   ┆ true       ┆ null            │
│ 2     ┆ Maria      ┆ Female ┆ 4/23/1993  ┆ … ┆ 130590 ┆ 11.858 ┆ false      ┆ Finance         │
│ 3     ┆ Jerry      ┆ Male   ┆ 3/4/2005   ┆ … ┆ 138705 ┆ 9.34   ┆ true       ┆ Finance         │
│ 4     ┆ Larry      ┆ Male   ┆ 1/24/1998  ┆ … ┆ 101004 ┆ 1.389  ┆ true       ┆ Client Services │
└───────┴────────────┴────────┴────────────┴───┴────────┴────────┴────────────┴─────────────────┘

In [7]:
df.head()

shape: (5, 8)
┌────────────┬────────┬────────────┬────────────┬────────┬────────┬────────────────────┬───────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login ┆ Salary ┆ Bonus  ┆ Senior Management  ┆ Team      │
│ ---        ┆ ---    ┆ ---        ┆ Time       ┆ ---    ┆ ---    ┆ ---                ┆ ---       │
│ str        ┆ str    ┆ str        ┆ ---        ┆ i64    ┆ f64    ┆ bool               ┆ str       │
│            ┆        ┆            ┆ str        ┆        ┆        ┆                    ┆           │
╞════════════╪════════╪════════════╪════════════╪════════╪════════╪════════════════════╪═══════════╡
│ Douglas    ┆ Male   ┆ 8/6/1993   ┆ 12:42 PM   ┆ 97308  ┆ 6.945  ┆ true               ┆ Marketing │
│ Thomas     ┆ Male   ┆ 3/31/1996  ┆ 6:53 AM    ┆ 61933  ┆ 4.17   ┆ true               ┆ null      │
│ Maria      ┆ Female ┆ 4/23/1993  ┆ 11:17 AM   ┆ 130590 ┆ 11.858 ┆ false              ┆ Finance   │
│ Jerry      ┆ Male   ┆ 3/4/2005   ┆ 1:00 PM    ┆ 138705 ┆ 9.34   ┆ true               ┆ Finance   │
│ Larry      ┆ Male   ┆ 1/24/1998  ┆ 4:47 PM    ┆ 101004 ┆ 1.389  ┆ true               ┆ Client    │
│            ┆        ┆            ┆            ┆        ┆        ┆                    ┆ Services  │
└────────────┴────────┴────────────┴────────────┴────────┴────────┴────────────────────┴───────────┘

In [9]:
## 특정 컬럼 데이터 선택

print(df[:10]['Gender'])

shape: (10,)
Series: 'Gender' [str]
[
	"Male"
	"Male"
	"Female"
	"Male"
	"Male"
	"Male"
	"Female"
	"Female"
	"Female"
	"Female"
]

In [10]:
## 여러 컬럼 선택

tmp1 = df[['Gender', 'Salary']]
tmp2 = df.select('Gender', 'Salary')
tmp1[:10], tmp2[:10]

(shape: (10, 2)
 ┌────────┬────────┐
 │ Gender ┆ Salary │
 │ ---    ┆ ---    │
 │ str    ┆ i64    │
 ╞════════╪════════╡
 │ Male   ┆ 97308  │
 │ Male   ┆ 61933  │
 │ Female ┆ 130590 │
 │ Male   ┆ 138705 │
 │ Male   ┆ 101004 │
 │ Male   ┆ 115163 │
 │ Female ┆ 65476  │
 │ Female ┆ 45906  │
 │ Female ┆ 95570  │
 │ Female ┆ 139852 │
 └────────┴────────┘,
 shape: (10, 2)
 ┌────────┬────────┐
 │ Gender ┆ Salary │
 │ ---    ┆ ---    │
 │ str    ┆ i64    │
 ╞════════╪════════╡
 │ Male   ┆ 97308  │
 │ Male   ┆ 61933  │
 │ Female ┆ 130590 │
 │ Male   ┆ 138705 │
 │ Male   ┆ 101004 │
 │ Male   ┆ 115163 │
 │ Female ┆ 65476  │
 │ Female ┆ 45906  │
 │ Female ┆ 95570  │
 │ Female ┆ 139852 │
 └────────┴────────┘)

In [ ]:
## 새로운 컬럼 생성
# df['surplus'] = df["Salary"]*df['Bonus']/100
# Bonus에 대한 금액 계산 컬럼(surplus) 추가
df.with_columns(
    (df["Salary"]*df['Bonus']/100).round(2).alias('surplus')
    )

# 아래 명령도 가능함

# df.with_columns(
#     (pl.col("Salary")*pl.col('Bonus')/100).round(2).alias('surplus')
#     )

# df.with_columns(
#     surplus = (pl.col("Salary")*pl.col('Bonus')/100).round(2)
#     )

shape: (1_000, 9)
┌────────────┬────────┬────────────┬─────────────┬───┬────────┬────────────┬────────────┬──────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login  ┆ … ┆ Bonus  ┆ Senior     ┆ Team       ┆ surplus  │
│ ---        ┆ ---    ┆ ---        ┆ Time        ┆   ┆ ---    ┆ Management ┆ ---        ┆ ---      │
│ str        ┆ str    ┆ str        ┆ ---         ┆   ┆ f64    ┆ ---        ┆ str        ┆ f64      │
│            ┆        ┆            ┆ str         ┆   ┆        ┆ bool       ┆            ┆          │
╞════════════╪════════╪════════════╪═════════════╪═══╪════════╪════════════╪════════════╪══════════╡
│ Douglas    ┆ Male   ┆ 8/6/1993   ┆ 12:42 PM    ┆ … ┆ 6.945  ┆ true       ┆ Marketing  ┆ 6758.04  │
│ Thomas     ┆ Male   ┆ 3/31/1996  ┆ 6:53 AM     ┆ … ┆ 4.17   ┆ true       ┆ null       ┆ 2582.61  │
│ Maria      ┆ Female ┆ 4/23/1993  ┆ 11:17 AM    ┆ … ┆ 11.858 ┆ false      ┆ Finance    ┆ 15485.36 │
│ Jerry      ┆ Male   ┆ 3/4/2005   ┆ 1:00 PM     ┆ … ┆ 9.34   ┆ true       ┆ Finance    ┆ 12955.05 │
│ Larry      ┆ Male   ┆ 1/24/1998  ┆ 4:47 PM     ┆ … ┆ 1.389  ┆ true       ┆ Client     ┆ 1402.95  │
│            ┆        ┆            ┆             ┆   ┆        ┆            ┆ Services   ┆          │
│ …          ┆ …      ┆ …          ┆ …           ┆ … ┆ …      ┆ …          ┆ …          ┆ …        │
│ Henry      ┆ null   ┆ 11/23/2014 ┆ 6:09 AM     ┆ … ┆ 16.655 ┆ false      ┆ Distributi ┆ 22065.04 │
│            ┆        ┆            ┆             ┆   ┆        ┆            ┆ on         ┆          │
│ Phillip    ┆ Male   ┆ 1/31/1984  ┆ 6:30 AM     ┆ … ┆ 19.675 ┆ false      ┆ Finance    ┆ 8340.63  │
│ Russell    ┆ Male   ┆ 5/20/2013  ┆ 12:39 PM    ┆ … ┆ 1.421  ┆ false      ┆ Product    ┆ 1377.15  │
│ Larry      ┆ Male   ┆ 4/20/2013  ┆ 4:45 PM     ┆ … ┆ 11.985 ┆ false      ┆ Business   ┆ 7250.93  │
│            ┆        ┆            ┆             ┆   ┆        ┆            ┆ Developmen ┆          │
│            ┆        ┆            ┆             ┆   ┆        ┆            ┆ t          ┆          │
│ Albert     ┆ Male   ┆ 5/15/2012  ┆ 6:24 PM     ┆ … ┆ 10.169 ┆ true       ┆ Sales      ┆ 13214.51 │
└────────────┴────────┴────────────┴─────────────┴───┴────────┴────────────┴────────────┴──────────┘

In [ ]:
## 컬럼 이름 변경

rename_dict = {
        'Bonus' : 'bonus',
        'Gender' : 'gender'
        }

df.rename(rename_dict).head()

shape: (5, 8)
┌────────────┬────────┬────────────┬────────────┬────────┬────────┬────────────────────┬───────────┐
│ First Name ┆ gender ┆ Start Date ┆ Last Login ┆ Salary ┆ bonus  ┆ Senior Management  ┆ Team      │
│ ---        ┆ ---    ┆ ---        ┆ Time       ┆ ---    ┆ ---    ┆ ---                ┆ ---       │
│ str        ┆ str    ┆ str        ┆ ---        ┆ i64    ┆ f64    ┆ bool               ┆ str       │
│            ┆        ┆            ┆ str        ┆        ┆        ┆                    ┆           │
╞════════════╪════════╪════════════╪════════════╪════════╪════════╪════════════════════╪═══════════╡
│ Douglas    ┆ Male   ┆ 8/6/1993   ┆ 12:42 PM   ┆ 97308  ┆ 6.945  ┆ true               ┆ Marketing │
│ Thomas     ┆ Male   ┆ 3/31/1996  ┆ 6:53 AM    ┆ 61933  ┆ 4.17   ┆ true               ┆ null      │
│ Maria      ┆ Female ┆ 4/23/1993  ┆ 11:17 AM   ┆ 130590 ┆ 11.858 ┆ false              ┆ Finance   │
│ Jerry      ┆ Male   ┆ 3/4/2005   ┆ 1:00 PM    ┆ 138705 ┆ 9.34   ┆ true               ┆ Finance   │
│ Larry      ┆ Male   ┆ 1/24/1998  ┆ 4:47 PM    ┆ 101004 ┆ 1.389  ┆ true               ┆ Client    │
│            ┆        ┆            ┆            ┆        ┆        ┆                    ┆ Services  │
└────────────┴────────┴────────────┴────────────┴────────┴────────┴────────────────────┴───────────┘

In [ ]:
## 컬럼 삭제

df.drop('Last Login Time')

shape: (1_000, 7)
┌────────────┬────────┬────────────┬────────┬────────┬───────────────────┬──────────────────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Salary ┆ Bonus  ┆ Senior Management ┆ Team                 │
│ ---        ┆ ---    ┆ ---        ┆ ---    ┆ ---    ┆ ---               ┆ ---                  │
│ str        ┆ str    ┆ str        ┆ i64    ┆ f64    ┆ bool              ┆ str                  │
╞════════════╪════════╪════════════╪════════╪════════╪═══════════════════╪══════════════════════╡
│ Douglas    ┆ Male   ┆ 8/6/1993   ┆ 97308  ┆ 6.945  ┆ true              ┆ Marketing            │
│ Thomas     ┆ Male   ┆ 3/31/1996  ┆ 61933  ┆ 4.17   ┆ true              ┆ null                 │
│ Maria      ┆ Female ┆ 4/23/1993  ┆ 130590 ┆ 11.858 ┆ false             ┆ Finance              │
│ Jerry      ┆ Male   ┆ 3/4/2005   ┆ 138705 ┆ 9.34   ┆ true              ┆ Finance              │
│ Larry      ┆ Male   ┆ 1/24/1998  ┆ 101004 ┆ 1.389  ┆ true              ┆ Client Services      │
│ …          ┆ …      ┆ …          ┆ …      ┆ …      ┆ …                 ┆ …                    │
│ Henry      ┆ null   ┆ 11/23/2014 ┆ 132483 ┆ 16.655 ┆ false             ┆ Distribution         │
│ Phillip    ┆ Male   ┆ 1/31/1984  ┆ 42392  ┆ 19.675 ┆ false             ┆ Finance              │
│ Russell    ┆ Male   ┆ 5/20/2013  ┆ 96914  ┆ 1.421  ┆ false             ┆ Product              │
│ Larry      ┆ Male   ┆ 4/20/2013  ┆ 60500  ┆ 11.985 ┆ false             ┆ Business Development │
│ Albert     ┆ Male   ┆ 5/15/2012  ┆ 129949 ┆ 10.169 ┆ true              ┆ Sales                │
└────────────┴────────┴────────────┴────────┴────────┴───────────────────┴──────────────────────┘

## 3. Null 값 다루기

In [ ]:
## 컬럼별 null 갯수 확인

df.null_count()

shape: (1, 8)
┌────────────┬────────┬────────────┬─────────────────┬────────┬───────┬───────────────────┬──────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login Time ┆ Salary ┆ Bonus ┆ Senior Management ┆ Team │
│ ---        ┆ ---    ┆ ---        ┆ ---             ┆ ---    ┆ ---   ┆ ---               ┆ ---  │
│ u32        ┆ u32    ┆ u32        ┆ u32             ┆ u32    ┆ u32   ┆ u32               ┆ u32  │
╞════════════╪════════╪════════════╪═════════════════╪════════╪═══════╪═══════════════════╪══════╡
│ 67         ┆ 145    ┆ 0          ┆ 0               ┆ 0      ┆ 0     ┆ 67                ┆ 43   │
└────────────┴────────┴────────────┴─────────────────┴────────┴───────┴───────────────────┴──────┘

In [ ]:
## 특정 컬럼 null값 확인

df['Gender'].is_null().sum()

145

In [ ]:
## null 채우기

df.fill_null(0)

# forward: 직전 값으로 채움, backward: 다음 값으로 채움

df.fill_null(strategy='forward') # 'forward', 'backward', 'min', 'max', 'mean', 'zero', 'one'

shape: (1_000, 8)
┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
│ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
│ str        ┆ str    ┆ str        ┆ ---           ┆ i64    ┆ f64    ┆ ---          ┆ str          │
│            ┆        ┆            ┆ str           ┆        ┆        ┆ bool         ┆              │
╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
│ Douglas    ┆ Male   ┆ 8/6/1993   ┆ 12:42 PM      ┆ 97308  ┆ 6.945  ┆ true         ┆ Marketing    │
│ Thomas     ┆ Male   ┆ 3/31/1996  ┆ 6:53 AM       ┆ 61933  ┆ 4.17   ┆ true         ┆ Marketing    │
│ Maria      ┆ Female ┆ 4/23/1993  ┆ 11:17 AM      ┆ 130590 ┆ 11.858 ┆ false        ┆ Finance      │
│ Jerry      ┆ Male   ┆ 3/4/2005   ┆ 1:00 PM       ┆ 138705 ┆ 9.34   ┆ true         ┆ Finance      │
│ Larry      ┆ Male   ┆ 1/24/1998  ┆ 4:47 PM       ┆ 101004 ┆ 1.389  ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ …          ┆ …      ┆ …          ┆ …             ┆ …      ┆ …      ┆ …            ┆ …            │
│ Henry      ┆ Male   ┆ 11/23/2014 ┆ 6:09 AM       ┆ 132483 ┆ 16.655 ┆ false        ┆ Distribution │
│ Phillip    ┆ Male   ┆ 1/31/1984  ┆ 6:30 AM       ┆ 42392  ┆ 19.675 ┆ false        ┆ Finance      │
│ Russell    ┆ Male   ┆ 5/20/2013  ┆ 12:39 PM      ┆ 96914  ┆ 1.421  ┆ false        ┆ Product      │
│ Larry      ┆ Male   ┆ 4/20/2013  ┆ 4:45 PM       ┆ 60500  ┆ 11.985 ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Albert     ┆ Male   ┆ 5/15/2012  ┆ 6:24 PM       ┆ 129949 ┆ 10.169 ┆ true         ┆ Sales        │
└────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘

In [ ]:
tmp = pl.DataFrame(
    {
        "a": [1, 2, None, 4],
        "b": [0.5, 4, None, 13],
    }
)

tmp.fill_null(strategy="backward")

shape: (4, 2)
┌─────┬──────┐
│ a   ┆ b    │
│ --- ┆ ---  │
│ i64 ┆ f64  │
╞═════╪══════╡
│ 1   ┆ 0.5  │
│ 2   ┆ 4.0  │
│ 4   ┆ 13.0 │
│ 4   ┆ 13.0 │
└─────┴──────┘

In [ ]:
## null 없애기

# 전체 컬럼 대상
df.drop_nulls()

# 특정 컬럼 대상
df.drop_nulls(subset='Gender')

# 특정 타입 대상
import polars.selectors as cs

df.drop_nulls(subset=cs.string())

shape: (764, 8)
┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
│ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
│ str        ┆ str    ┆ str        ┆ ---           ┆ i64    ┆ f64    ┆ ---          ┆ str          │
│            ┆        ┆            ┆ str           ┆        ┆        ┆ bool         ┆              │
╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
│ Douglas    ┆ Male   ┆ 8/6/1993   ┆ 12:42 PM      ┆ 97308  ┆ 6.945  ┆ true         ┆ Marketing    │
│ Maria      ┆ Female ┆ 4/23/1993  ┆ 11:17 AM      ┆ 130590 ┆ 11.858 ┆ false        ┆ Finance      │
│ Jerry      ┆ Male   ┆ 3/4/2005   ┆ 1:00 PM       ┆ 138705 ┆ 9.34   ┆ true         ┆ Finance      │
│ Larry      ┆ Male   ┆ 1/24/1998  ┆ 4:47 PM       ┆ 101004 ┆ 1.389  ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Dennis     ┆ Male   ┆ 4/18/1987  ┆ 1:35 AM       ┆ 115163 ┆ 10.125 ┆ false        ┆ Legal        │
│ …          ┆ …      ┆ …          ┆ …             ┆ …      ┆ …      ┆ …            ┆ …            │
│ George     ┆ Male   ┆ 6/21/2013  ┆ 5:47 PM       ┆ 98874  ┆ 4.479  ┆ true         ┆ Marketing    │
│ Phillip    ┆ Male   ┆ 1/31/1984  ┆ 6:30 AM       ┆ 42392  ┆ 19.675 ┆ false        ┆ Finance      │
│ Russell    ┆ Male   ┆ 5/20/2013  ┆ 12:39 PM      ┆ 96914  ┆ 1.421  ┆ false        ┆ Product      │
│ Larry      ┆ Male   ┆ 4/20/2013  ┆ 4:45 PM       ┆ 60500  ┆ 11.985 ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Albert     ┆ Male   ┆ 5/15/2012  ┆ 6:24 PM       ┆ 129949 ┆ 10.169 ┆ true         ┆ Sales        │
└────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘

## 4. 데이터 타입 다루기

In [ ]:
# INT -> STRING 변경

df = df.with_columns(
    Salary = pl.col("Salary").cast(pl.String)
    )

In [ ]:
# STRING -> INT 변경

df = df.with_columns(
    Salary = pl.col("Salary").cast(pl.Int32)
    )

In [ ]:
# Start Date를 datetime 형식으로 변환
df = df.with_columns(
    pl.col("Start Date").str.strptime(pl.Date, format="%m/%d/%Y").alias("Start Date")
    )

# Last Login Time을 시간 형식으로 변환
df = df.with_columns(
    pl.col("Last Login Time").str.strptime(pl.Time, format="%I:%M %p").alias("Last Login Time")
    )

In [ ]:
# 년, 월, 일 추출

df.with_columns(
    year = pl.col("Start Date").dt.year(),
    month = pl.col("Start Date").dt.month(),
    day = pl.col("Start Date").dt.day()
    ).head()

shape: (5, 11)
┌────────────┬────────┬────────────┬─────────────────┬───┬─────────────────┬──────┬───────┬─────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login Time ┆ … ┆ Team            ┆ year ┆ month ┆ day │
│ ---        ┆ ---    ┆ ---        ┆ ---             ┆   ┆ ---             ┆ ---  ┆ ---   ┆ --- │
│ str        ┆ str    ┆ date       ┆ time            ┆   ┆ str             ┆ i32  ┆ i8    ┆ i8  │
╞════════════╪════════╪════════════╪═════════════════╪═══╪═════════════════╪══════╪═══════╪═════╡
│ Douglas    ┆ Male   ┆ 1993-08-06 ┆ 12:42:00        ┆ … ┆ Marketing       ┆ 1993 ┆ 8     ┆ 6   │
│ Thomas     ┆ Male   ┆ 1996-03-31 ┆ 06:53:00        ┆ … ┆ null            ┆ 1996 ┆ 3     ┆ 31  │
│ Maria      ┆ Female ┆ 1993-04-23 ┆ 11:17:00        ┆ … ┆ Finance         ┆ 1993 ┆ 4     ┆ 23  │
│ Jerry      ┆ Male   ┆ 2005-03-04 ┆ 13:00:00        ┆ … ┆ Finance         ┆ 2005 ┆ 3     ┆ 4   │
│ Larry      ┆ Male   ┆ 1998-01-24 ┆ 16:47:00        ┆ … ┆ Client Services ┆ 1998 ┆ 1     ┆ 24  │
└────────────┴────────┴────────────┴─────────────────┴───┴─────────────────┴──────┴───────┴─────┘

## 5. 데이터 필터링

In [ ]:
df.head()

shape: (5, 8)
┌────────────┬────────┬────────────┬────────────┬────────┬────────┬────────────────────┬───────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login ┆ Salary ┆ Bonus  ┆ Senior Management  ┆ Team      │
│ ---        ┆ ---    ┆ ---        ┆ Time       ┆ ---    ┆ ---    ┆ ---                ┆ ---       │
│ str        ┆ str    ┆ date       ┆ ---        ┆ i32    ┆ f64    ┆ bool               ┆ str       │
│            ┆        ┆            ┆ time       ┆        ┆        ┆                    ┆           │
╞════════════╪════════╪════════════╪════════════╪════════╪════════╪════════════════════╪═══════════╡
│ Douglas    ┆ Male   ┆ 1993-08-06 ┆ 12:42:00   ┆ 97308  ┆ 6.945  ┆ true               ┆ Marketing │
│ Thomas     ┆ Male   ┆ 1996-03-31 ┆ 06:53:00   ┆ 61933  ┆ 4.17   ┆ true               ┆ null      │
│ Maria      ┆ Female ┆ 1993-04-23 ┆ 11:17:00   ┆ 130590 ┆ 11.858 ┆ false              ┆ Finance   │
│ Jerry      ┆ Male   ┆ 2005-03-04 ┆ 13:00:00   ┆ 138705 ┆ 9.34   ┆ true               ┆ Finance   │
│ Larry      ┆ Male   ┆ 1998-01-24 ┆ 16:47:00   ┆ 101004 ┆ 1.389  ┆ true               ┆ Client    │
│            ┆        ┆            ┆            ┆        ┆        ┆                    ┆ Services  │
└────────────┴────────┴────────────┴────────────┴────────┴────────┴────────────────────┴───────────┘

In [ ]:
## 단일 조건 필터

df.filter(pl.col('Gender').is_null())

shape: (145, 8)
┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
│ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
│ str        ┆ str    ┆ date       ┆ ---           ┆ i32    ┆ f64    ┆ ---          ┆ str          │
│            ┆        ┆            ┆ time          ┆        ┆        ┆ bool         ┆              │
╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
│ Lois       ┆ null   ┆ 1995-04-22 ┆ 19:18:00      ┆ 64714  ┆ 4.934  ┆ true         ┆ Legal        │
│ Joshua     ┆ null   ┆ 2012-03-08 ┆ 01:58:00      ┆ 90816  ┆ 18.816 ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Scott      ┆ null   ┆ 1991-07-11 ┆ 18:58:00      ┆ 122367 ┆ 5.218  ┆ false        ┆ Legal        │
│ Joyce      ┆ null   ┆ 2005-02-20 ┆ 14:40:00      ┆ 88657  ┆ 12.752 ┆ false        ┆ Product      │
│ Christine  ┆ null   ┆ 2015-06-28 ┆ 01:08:00      ┆ 66582  ┆ 11.308 ┆ true         ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ …          ┆ …      ┆ …          ┆ …             ┆ …      ┆ …      ┆ …            ┆ …            │
│ Antonio    ┆ null   ┆ 1989-06-18 ┆ 21:37:00      ┆ 103050 ┆ 3.05   ┆ false        ┆ Legal        │
│ Victor     ┆ null   ┆ 2006-07-28 ┆ 14:49:00      ┆ 76381  ┆ 11.159 ┆ true         ┆ Sales        │
│ Stephen    ┆ null   ┆ 1983-07-10 ┆ 20:10:00      ┆ 85668  ┆ 1.909  ┆ false        ┆ Legal        │
│ Justin     ┆ null   ┆ 1991-02-10 ┆ 16:58:00      ┆ 38344  ┆ 3.794  ┆ false        ┆ Legal        │
│ Henry      ┆ null   ┆ 2014-11-23 ┆ 06:09:00      ┆ 132483 ┆ 16.655 ┆ false        ┆ Distribution │
└────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘

In [ ]:

#df.filter(pl.col('Gender') == 'Female')

df.filter(pl.col('Bonus') >= 10)

# df.filter(pl.col('Bonus').is_between(8, 12))

# df.filter(pl.col('Team').is_in(['Finance', 'Sales']))

shape: (495, 8)
┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
│ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
│ str        ┆ str    ┆ date       ┆ ---           ┆ i32    ┆ f64    ┆ ---          ┆ str          │
│            ┆        ┆            ┆ time          ┆        ┆        ┆ bool         ┆              │
╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
│ Maria      ┆ Female ┆ 1993-04-23 ┆ 11:17:00      ┆ 130590 ┆ 11.858 ┆ false        ┆ Finance      │
│ Dennis     ┆ Male   ┆ 1987-04-18 ┆ 01:35:00      ┆ 115163 ┆ 10.125 ┆ false        ┆ Legal        │
│ Ruby       ┆ Female ┆ 1987-08-17 ┆ 16:20:00      ┆ 65476  ┆ 10.012 ┆ true         ┆ Product      │
│ null       ┆ Female ┆ 2015-07-20 ┆ 10:43:00      ┆ 45906  ┆ 11.598 ┆ null         ┆ Finance      │
│ Angela     ┆ Female ┆ 2005-11-22 ┆ 06:29:00      ┆ 95570  ┆ 18.523 ┆ true         ┆ Engineering  │
│ …          ┆ …      ┆ …          ┆ …             ┆ …      ┆ …      ┆ …            ┆ …            │
│ Tina       ┆ Female ┆ 1997-05-15 ┆ 15:53:00      ┆ 56450  ┆ 19.04  ┆ true         ┆ Engineering  │
│ Henry      ┆ null   ┆ 2014-11-23 ┆ 06:09:00      ┆ 132483 ┆ 16.655 ┆ false        ┆ Distribution │
│ Phillip    ┆ Male   ┆ 1984-01-31 ┆ 06:30:00      ┆ 42392  ┆ 19.675 ┆ false        ┆ Finance      │
│ Larry      ┆ Male   ┆ 2013-04-20 ┆ 16:45:00      ┆ 60500  ┆ 11.985 ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Albert     ┆ Male   ┆ 2012-05-15 ┆ 18:24:00      ┆ 129949 ┆ 10.169 ┆ true         ┆ Sales        │
└────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘

In [ ]:
## 다중 필터

and_condition = (pl.col('Gender') == 'Female') & (pl.col('Bonus') >= 10)

or_condition = (pl.col('Gender') == 'Female') | (pl.col('Bonus') >= 10)

df.filter(and_condition)

shape: (202, 8)
┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
│ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
│ str        ┆ str    ┆ date       ┆ ---           ┆ i32    ┆ f64    ┆ ---          ┆ str          │
│            ┆        ┆            ┆ time          ┆        ┆        ┆ bool         ┆              │
╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
│ Maria      ┆ Female ┆ 1993-04-23 ┆ 11:17:00      ┆ 130590 ┆ 11.858 ┆ false        ┆ Finance      │
│ Ruby       ┆ Female ┆ 1987-08-17 ┆ 16:20:00      ┆ 65476  ┆ 10.012 ┆ true         ┆ Product      │
│ null       ┆ Female ┆ 2015-07-20 ┆ 10:43:00      ┆ 45906  ┆ 11.598 ┆ null         ┆ Finance      │
│ Angela     ┆ Female ┆ 2005-11-22 ┆ 06:29:00      ┆ 95570  ┆ 18.523 ┆ true         ┆ Engineering  │
│ Louise     ┆ Female ┆ 1980-08-12 ┆ 09:01:00      ┆ 63241  ┆ 15.132 ┆ true         ┆ null         │
│ …          ┆ …      ┆ …          ┆ …             ┆ …      ┆ …      ┆ …            ┆ …            │
│ Gloria     ┆ Female ┆ 2014-12-08 ┆ 05:08:00      ┆ 136709 ┆ 10.331 ┆ true         ┆ Finance      │
│ Alice      ┆ Female ┆ 2004-10-05 ┆ 09:34:00      ┆ 47638  ┆ 11.209 ┆ false        ┆ Human        │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Resources    │
│ Robin      ┆ Female ┆ 1987-07-24 ┆ 13:35:00      ┆ 100765 ┆ 10.982 ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Rose       ┆ Female ┆ 2002-08-25 ┆ 05:12:00      ┆ 134505 ┆ 11.051 ┆ true         ┆ Marketing    │
│ Tina       ┆ Female ┆ 1997-05-15 ┆ 15:53:00      ┆ 56450  ┆ 19.04  ┆ true         ┆ Engineering  │
└────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘

In [ ]:
df.head()

shape: (5, 8)
┌────────────┬────────┬────────────┬────────────┬────────┬────────┬────────────────────┬───────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login ┆ Salary ┆ Bonus  ┆ Senior Management  ┆ Team      │
│ ---        ┆ ---    ┆ ---        ┆ Time       ┆ ---    ┆ ---    ┆ ---                ┆ ---       │
│ str        ┆ str    ┆ date       ┆ ---        ┆ i32    ┆ f64    ┆ bool               ┆ str       │
│            ┆        ┆            ┆ time       ┆        ┆        ┆                    ┆           │
╞════════════╪════════╪════════════╪════════════╪════════╪════════╪════════════════════╪═══════════╡
│ Douglas    ┆ Male   ┆ 1993-08-06 ┆ 12:42:00   ┆ 97308  ┆ 6.945  ┆ true               ┆ Marketing │
│ Thomas     ┆ Male   ┆ 1996-03-31 ┆ 06:53:00   ┆ 61933  ┆ 4.17   ┆ true               ┆ null      │
│ Maria      ┆ Female ┆ 1993-04-23 ┆ 11:17:00   ┆ 130590 ┆ 11.858 ┆ false              ┆ Finance   │
│ Jerry      ┆ Male   ┆ 2005-03-04 ┆ 13:00:00   ┆ 138705 ┆ 9.34   ┆ true               ┆ Finance   │
│ Larry      ┆ Male   ┆ 1998-01-24 ┆ 16:47:00   ┆ 101004 ┆ 1.389  ┆ true               ┆ Client    │
│            ┆        ┆            ┆            ┆        ┆        ┆                    ┆ Services  │
└────────────┴────────┴────────────┴────────────┴────────┴────────┴────────────────────┴───────────┘

In [ ]:
df.with_columns(
    tmp = pl.when(pl.col("Team").is_in(['Marketing', 'Engineering'])).then(pl.lit("P")).otherwise(pl.lit("O"))
)

shape: (1_000, 9)
┌────────────┬────────┬────────────┬──────────────┬───┬────────┬──────────────┬──────────────┬─────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login   ┆ … ┆ Bonus  ┆ Senior       ┆ Team         ┆ tmp │
│ ---        ┆ ---    ┆ ---        ┆ Time         ┆   ┆ ---    ┆ Management   ┆ ---          ┆ --- │
│ str        ┆ str    ┆ date       ┆ ---          ┆   ┆ f64    ┆ ---          ┆ str          ┆ str │
│            ┆        ┆            ┆ time         ┆   ┆        ┆ bool         ┆              ┆     │
╞════════════╪════════╪════════════╪══════════════╪═══╪════════╪══════════════╪══════════════╪═════╡
│ Douglas    ┆ Male   ┆ 1993-08-06 ┆ 12:42:00     ┆ … ┆ 6.945  ┆ true         ┆ Marketing    ┆ P   │
│ Thomas     ┆ Male   ┆ 1996-03-31 ┆ 06:53:00     ┆ … ┆ 4.17   ┆ true         ┆ null         ┆ O   │
│ Maria      ┆ Female ┆ 1993-04-23 ┆ 11:17:00     ┆ … ┆ 11.858 ┆ false        ┆ Finance      ┆ O   │
│ Jerry      ┆ Male   ┆ 2005-03-04 ┆ 13:00:00     ┆ … ┆ 9.34   ┆ true         ┆ Finance      ┆ O   │
│ Larry      ┆ Male   ┆ 1998-01-24 ┆ 16:47:00     ┆ … ┆ 1.389  ┆ true         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Dennis     ┆ Male   ┆ 1987-04-18 ┆ 01:35:00     ┆ … ┆ 10.125 ┆ false        ┆ Legal        ┆ O   │
│ Ruby       ┆ Female ┆ 1987-08-17 ┆ 16:20:00     ┆ … ┆ 10.012 ┆ true         ┆ Product      ┆ O   │
│ null       ┆ Female ┆ 2015-07-20 ┆ 10:43:00     ┆ … ┆ 11.598 ┆ null         ┆ Finance      ┆ O   │
│ Angela     ┆ Female ┆ 2005-11-22 ┆ 06:29:00     ┆ … ┆ 18.523 ┆ true         ┆ Engineering  ┆ P   │
│ Frances    ┆ Female ┆ 2002-08-08 ┆ 06:51:00     ┆ … ┆ 7.524  ┆ true         ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Louise     ┆ Female ┆ 1980-08-12 ┆ 09:01:00     ┆ … ┆ 15.132 ┆ true         ┆ null         ┆ O   │
│ Julie      ┆ Female ┆ 1997-10-26 ┆ 15:19:00     ┆ … ┆ 12.637 ┆ true         ┆ Legal        ┆ O   │
│ Brandon    ┆ Male   ┆ 1980-12-01 ┆ 01:08:00     ┆ … ┆ 17.492 ┆ true         ┆ Human        ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Resources    ┆     │
│ Gary       ┆ Male   ┆ 2008-01-27 ┆ 23:40:00     ┆ … ┆ 5.831  ┆ false        ┆ Sales        ┆ O   │
│ Kimberly   ┆ Female ┆ 1999-01-14 ┆ 07:13:00     ┆ … ┆ 14.543 ┆ true         ┆ Finance      ┆ O   │
│ Lillian    ┆ Female ┆ 2016-06-05 ┆ 06:09:00     ┆ … ┆ 1.256  ┆ false        ┆ Product      ┆ O   │
│ Jeremy     ┆ Male   ┆ 2010-09-21 ┆ 05:56:00     ┆ … ┆ 7.369  ┆ false        ┆ Human        ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Resources    ┆     │
│ Shawn      ┆ Male   ┆ 1986-12-07 ┆ 19:45:00     ┆ … ┆ 6.414  ┆ false        ┆ Product      ┆ O   │
│ Diana      ┆ Female ┆ 1981-10-23 ┆ 10:27:00     ┆ … ┆ 19.082 ┆ false        ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Donna      ┆ Female ┆ 2010-07-22 ┆ 03:48:00     ┆ … ┆ 1.894  ┆ false        ┆ Product      ┆ O   │
│ Lois       ┆ null   ┆ 1995-04-22 ┆ 19:18:00     ┆ … ┆ 4.934  ┆ true         ┆ Legal        ┆ O   │
│ Matthew    ┆ Male   ┆ 1995-09-05 ┆ 02:12:00     ┆ … ┆ 13.645 ┆ false        ┆ Marketing    ┆ P   │
│ Joshua     ┆ null   ┆ 2012-03-08 ┆ 01:58:00     ┆ … ┆ 18.816 ┆ true         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ null       ┆ Male   ┆ 2012-06-14 ┆ 16:19:00     ┆ … ┆ 5.042  ┆ null         ┆ null         ┆ O   │
│ John       ┆ Male   ┆ 1992-07-01 ┆ 22:08:00     ┆ … ┆ 13.873 ┆ false        ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ null       ┆ Male   ┆ 2012-10-08 ┆ 01:12:00     ┆ … ┆ 18.576 ┆ null         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Craig      ┆ Male   ┆ 2000-02-27 ┆ 07:45:00     ┆ … ┆ 7.757  ┆ true         ┆ Marketing    ┆ P   │
│ Scott      ┆ null   ┆ 1991-07-11 ┆ 18:58:00     ┆ … ┆ 5.218  ┆ false        ┆ Legal        ┆ O   │
│ Terry      ┆ Male   ┆ 1981-11-27 ┆ 18:30:00     ┆ … ┆ 13.464 ┆ true         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Benjamin   ┆ Male   ┆ 2005-01-26 ┆ 22:06:00     ┆ … ┆ 7.008  ┆ true         ┆ Legal        ┆ O   │
│ Christina  ┆ Female ┆ 2002-08-06 ┆ 13:19:00     ┆ … ┆ 9.096  ┆ true         ┆ Engineering  ┆ P   │
│ Joyce      ┆ null   ┆ 2005-02-20 ┆ 14:40:00     ┆ … ┆ 12.752 ┆ false        ┆ Product      ┆ O   │
│ null       ┆ Male   ┆ 1998-08-21 ┆ 14:27:00     ┆ … ┆ 6.417  ┆ null         ┆ null         ┆ O   │
│ Jean       ┆ Female ┆ 1993-12-18 ┆ 09:07:00     ┆ … ┆ 16.18  ┆ false        ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Jerry      ┆ Male   ┆ 2004-01-10 ┆ 12:56:00     ┆ … ┆ 19.096 ┆ false        ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Theresa    ┆ Female ┆ 2006-10-10 ┆ 01:12:00     ┆ … ┆ 16.675 ┆ false        ┆ Sales        ┆ O   │
│ Rachel     ┆ Female ┆ 2009-02-16 ┆ 20:47:00     ┆ … ┆ 12.599 ┆ false        ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Linda      ┆ Female ┆ 1981-10-19 ┆ 20:49:00     ┆ … ┆ 9.557  ┆ true         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Stephanie  ┆ Female ┆ 1986-09-13 ┆ 01:52:00     ┆ … ┆ 5.574  ┆ true         ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ null       ┆ Male   ┆ 2016-01-29 ┆ 02:33:00     ┆ … ┆ 7.797  ┆ null         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Michael    ┆ Male   ┆ 2008-10-10 ┆ 11:25:00     ┆ … ┆ 2.665  ┆ true         ┆ Distribution ┆ O   │
│ Christine  ┆ null   ┆ 2015-06-28 ┆ 01:08:00     ┆ … ┆ 11.308 ┆ true         ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Beverly    ┆ Female ┆ 1998-09-09 ┆ 20:26:00     ┆ … ┆ 15.835 ┆ false        ┆ Legal        ┆ O   │
│ Marilyn    ┆ Female ┆ 1980-12-07 ┆ 03:16:00     ┆ … ┆ 5.207  ┆ true         ┆ Marketing    ┆ P   │
│ Cynthia    ┆ Female ┆ 1988-11-16 ┆ 18:54:00     ┆ … ┆ 7.482  ┆ true         ┆ Product      ┆ O   │
│ Roger      ┆ Male   ┆ 1980-04-17 ┆ 11:32:00     ┆ … ┆ 13.886 ┆ true         ┆ Sales        ┆ O   │
│ Bruce      ┆ Male   ┆ 2009-11-28 ┆ 22:47:00     ┆ … ┆ 6.796  ┆ false        ┆ Finance      ┆ O   │
│ Kathy      ┆ Female ┆ 2005-06-22 ┆ 04:51:00     ┆ … ┆ 9.0    ┆ true         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Clarence   ┆ Male   ┆ 1996-03-26 ┆ 05:57:00     ┆ … ┆ 6.083  ┆ true         ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Chris      ┆ null   ┆ 1980-01-24 ┆ 12:13:00     ┆ … ┆ 3.055  ┆ false        ┆ Sales        ┆ O   │
│ …          ┆ …      ┆ …          ┆ …            ┆ … ┆ …      ┆ …            ┆ …            ┆ …   │
│ Paula      ┆ Female ┆ 1983-05-21 ┆ 11:42:00     ┆ … ┆ 10.833 ┆ false        ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ null       ┆ Female ┆ 2010-09-14 ┆ 05:19:00     ┆ … ┆ 9.662  ┆ null         ┆ null         ┆ O   │
│ Teresa     ┆ Female ┆ 2013-01-22 ┆ 15:17:00     ┆ … ┆ 11.907 ┆ true         ┆ Human        ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Resources    ┆     │
│ Randy      ┆ Male   ┆ 2012-02-25 ┆ 05:33:00     ┆ … ┆ 14.077 ┆ false        ┆ Product      ┆ O   │
│ Joe        ┆ Male   ┆ 1980-01-19 ┆ 16:06:00     ┆ … ┆ 1.148  ┆ true         ┆ Finance      ┆ O   │
│ Sarah      ┆ Female ┆ 2014-08-17 ┆ 23:08:00     ┆ … ┆ 11.176 ┆ false        ┆ Legal        ┆ O   │
│ Beverly    ┆ Female ┆ 1986-10-17 ┆ 00:51:00     ┆ … ┆ 8.115  ┆ false        ┆ Engineering  ┆ P   │
│ Jeffrey    ┆ Male   ┆ 1984-02-03 ┆ 13:26:00     ┆ … ┆ 15.901 ┆ true         ┆ Sales        ┆ O   │
│ Gloria     ┆ Female ┆ 1987-10-24 ┆ 04:43:00     ┆ … ┆ 9.631  ┆ false        ┆ Engineering  ┆ P   │
│ Albert     ┆ Male   ┆ 1992-09-19 ┆ 02:35:00     ┆ … ┆ 5.85   ┆ true         ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Stephen    ┆ Male   ┆ 1989-10-29 ┆ 23:34:00     ┆ … ┆ 18.093 ┆ true         ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Antonio    ┆ null   ┆ 1989-06-18 ┆ 21:37:00     ┆ … ┆ 3.05   ┆ false        ┆ Legal        ┆ O   │
│ Jonathan   ┆ Male   ┆ 2013-08-21 ┆ 00:45:00     ┆ … ┆ 16.923 ┆ false        ┆ Product      ┆ O   │
│ Ann        ┆ Female ┆ 1994-09-23 ┆ 11:15:00     ┆ … ┆ 17.94  ┆ true         ┆ Sales        ┆ O   │
│ Bruce      ┆ Male   ┆ 1980-05-07 ┆ 20:00:00     ┆ … ┆ 12.391 ┆ true         ┆ Sales        ┆ O   │
│ Catherine  ┆ Female ┆ 1989-09-25 ┆ 01:31:00     ┆ … ┆ 18.393 ┆ false        ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Louis      ┆ Male   ┆ 2011-08-16 ┆ 17:19:00     ┆ … ┆ 9.146  ┆ true         ┆ Human        ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Resources    ┆     │
│ Thomas     ┆ Male   ┆ 2016-03-12 ┆ 15:10:00     ┆ … ┆ 19.572 ┆ false        ┆ Engineering  ┆ P   │
│ Louise     ┆ Female ┆ 1995-03-27 ┆ 22:27:00     ┆ … ┆ 11.671 ┆ false        ┆ Distribution ┆ O   │
│ Linda      ┆ Female ┆ 2010-02-04 ┆ 20:49:00     ┆ … ┆ 17.308 ┆ true         ┆ Engineering  ┆ P   │
│ Alice      ┆ Female ┆ 1988-09-03 ┆ 20:54:00     ┆ … ┆ 15.397 ┆ true         ┆ Product      ┆ O   │
│ Patrick    ┆ Male   ┆ 2002-12-30 ┆ 02:01:00     ┆ … ┆ 5.368  ┆ true         ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Victor     ┆ null   ┆ 2006-07-28 ┆ 14:49:00     ┆ … ┆ 11.159 ┆ true         ┆ Sales        ┆ O   │
│ Russell    ┆ Male   ┆ 2013-05-10 ┆ 23:08:00     ┆ … ┆ 11.105 ┆ false        ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Harry      ┆ Male   ┆ 2011-08-30 ┆ 18:31:00     ┆ … ┆ 16.455 ┆ true         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Susan      ┆ Female ┆ 1995-04-07 ┆ 22:05:00     ┆ … ┆ 12.467 ┆ false        ┆ Sales        ┆ O   │
│ Denise     ┆ Female ┆ 1992-10-19 ┆ 05:42:00     ┆ … ┆ 4.195  ┆ true         ┆ Legal        ┆ O   │
│ Sarah      ┆ Female ┆ 1995-12-04 ┆ 09:16:00     ┆ … ┆ 5.949  ┆ false        ┆ Product      ┆ O   │
│ Sean       ┆ Male   ┆ 1983-01-17 ┆ 14:23:00     ┆ … ┆ 11.178 ┆ false        ┆ Human        ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Resources    ┆     │
│ Ernest     ┆ Male   ┆ 2013-07-20 ┆ 06:41:00     ┆ … ┆ 13.198 ┆ true         ┆ Product      ┆ O   │
│ Kimberly   ┆ Female ┆ 2013-01-26 ┆ 00:57:00     ┆ … ┆ 8.862  ┆ true         ┆ Engineering  ┆ P   │
│ James      ┆ Male   ┆ 1993-01-15 ┆ 17:19:00     ┆ … ┆ 19.28  ┆ false        ┆ Legal        ┆ O   │
│ Rose       ┆ Female ┆ 1982-04-06 ┆ 10:43:00     ┆ … ┆ 8.639  ┆ true         ┆ Human        ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Resources    ┆     │
│ John       ┆ Male   ┆ 1982-12-23 ┆ 22:35:00     ┆ … ┆ 11.738 ┆ false        ┆ Engineering  ┆ P   │
│ Maria      ┆ Female ┆ 2011-10-15 ┆ 16:53:00     ┆ … ┆ 13.04  ┆ false        ┆ Engineering  ┆ P   │
│ Stephen    ┆ null   ┆ 1983-07-10 ┆ 20:10:00     ┆ … ┆ 1.909  ┆ false        ┆ Legal        ┆ O   │
│ Donna      ┆ Female ┆ 1982-11-26 ┆ 07:04:00     ┆ … ┆ 17.999 ┆ false        ┆ Marketing    ┆ P   │
│ Gloria     ┆ Female ┆ 2014-12-08 ┆ 05:08:00     ┆ … ┆ 10.331 ┆ true         ┆ Finance      ┆ O   │
│ Alice      ┆ Female ┆ 2004-10-05 ┆ 09:34:00     ┆ … ┆ 11.209 ┆ false        ┆ Human        ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Resources    ┆     │
│ Justin     ┆ null   ┆ 1991-02-10 ┆ 16:58:00     ┆ … ┆ 3.794  ┆ false        ┆ Legal        ┆ O   │
│ Robin      ┆ Female ┆ 1987-07-24 ┆ 13:35:00     ┆ … ┆ 10.982 ┆ true         ┆ Client       ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Services     ┆     │
│ Rose       ┆ Female ┆ 2002-08-25 ┆ 05:12:00     ┆ … ┆ 11.051 ┆ true         ┆ Marketing    ┆ P   │
│ Anthony    ┆ Male   ┆ 2011-10-16 ┆ 08:35:00     ┆ … ┆ 11.625 ┆ true         ┆ Finance      ┆ O   │
│ Tina       ┆ Female ┆ 1997-05-15 ┆ 15:53:00     ┆ … ┆ 19.04  ┆ true         ┆ Engineering  ┆ P   │
│ George     ┆ Male   ┆ 2013-06-21 ┆ 17:47:00     ┆ … ┆ 4.479  ┆ true         ┆ Marketing    ┆ P   │
│ Henry      ┆ null   ┆ 2014-11-23 ┆ 06:09:00     ┆ … ┆ 16.655 ┆ false        ┆ Distribution ┆ O   │
│ Phillip    ┆ Male   ┆ 1984-01-31 ┆ 06:30:00     ┆ … ┆ 19.675 ┆ false        ┆ Finance      ┆ O   │
│ Russell    ┆ Male   ┆ 2013-05-20 ┆ 12:39:00     ┆ … ┆ 1.421  ┆ false        ┆ Product      ┆ O   │
│ Larry      ┆ Male   ┆ 2013-04-20 ┆ 16:45:00     ┆ … ┆ 11.985 ┆ false        ┆ Business     ┆ O   │
│            ┆        ┆            ┆              ┆   ┆        ┆              ┆ Development  ┆     │
│ Albert     ┆ Male   ┆ 2012-05-15 ┆ 18:24:00     ┆ … ┆ 10.169 ┆ true         ┆ Sales        ┆ O   │
└────────────┴────────┴────────────┴──────────────┴───┴────────┴──────────────┴──────────────┴─────┘

## 6. ORDER BY

In [ ]:
## 단일 컬럼 정렬

df.sort('Bonus')

df.sort(
    by='Bonus',
    descending=True
    )

shape: (1_000, 8)
┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
│ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
│ str        ┆ str    ┆ date       ┆ ---           ┆ i32    ┆ f64    ┆ ---          ┆ str          │
│            ┆        ┆            ┆ time          ┆        ┆        ┆ bool         ┆              │
╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
│ Robert     ┆ Male   ┆ 2007-03-11 ┆ 11:20:00      ┆ 135882 ┆ 19.944 ┆ false        ┆ Legal        │
│ Sean       ┆ Male   ┆ 1996-05-04 ┆ 20:59:00      ┆ 135490 ┆ 19.934 ┆ false        ┆ Marketing    │
│ Robert     ┆ Male   ┆ 2014-11-18 ┆ 05:00:00      ┆ 85799  ┆ 19.93  ┆ false        ┆ Finance      │
│ Michael    ┆ Male   ┆ 2002-08-31 ┆ 01:20:00      ┆ 81206  ┆ 19.908 ┆ true         ┆ Distribution │
│ Philip     ┆ Male   ┆ 1989-08-02 ┆ 11:21:00      ┆ 129968 ┆ 19.897 ┆ false        ┆ Finance      │
│ Robert     ┆ Male   ┆ 1994-10-29 ┆ 04:26:00      ┆ 123294 ┆ 19.894 ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Rose       ┆ Female ┆ 1982-12-31 ┆ 18:50:00      ┆ 145001 ┆ 19.85  ┆ false        ┆ Engineering  │
│ Elizabeth  ┆ Female ┆ 2010-02-21 ┆ 07:02:00      ┆ 79145  ┆ 19.78  ┆ false        ┆ Finance      │
│ Evelyn     ┆ Female ┆ 2002-02-10 ┆ 04:44:00      ┆ 123621 ┆ 19.767 ┆ true         ┆ Marketing    │
│ George     ┆ Male   ┆ 1995-09-27 ┆ 17:04:00      ┆ 36749  ┆ 19.754 ┆ false        ┆ Finance      │
│ Sharon     ┆ Female ┆ 2011-07-01 ┆ 09:50:00      ┆ 46007  ┆ 19.731 ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Albert     ┆ Male   ┆ 1997-02-01 ┆ 16:20:00      ┆ 67827  ┆ 19.717 ┆ true         ┆ Engineering  │
│ Wanda      ┆ Female ┆ 1993-04-06 ┆ 03:11:00      ┆ 78883  ┆ 19.695 ┆ false        ┆ null         │
│ Willie     ┆ Male   ┆ 2009-08-22 ┆ 13:03:00      ┆ 55038  ┆ 19.691 ┆ false        ┆ Legal        │
│ Henry      ┆ Male   ┆ 1995-04-24 ┆ 04:18:00      ┆ 43542  ┆ 19.687 ┆ false        ┆ Legal        │
│ Phillip    ┆ Male   ┆ 1984-01-31 ┆ 06:30:00      ┆ 42392  ┆ 19.675 ┆ false        ┆ Finance      │
│ Craig      ┆ Male   ┆ 1984-02-08 ┆ 04:45:00      ┆ 113506 ┆ 19.642 ┆ false        ┆ Marketing    │
│ Martha     ┆ Female ┆ 1997-07-17 ┆ 23:11:00      ┆ 94963  ┆ 19.626 ┆ true         ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Jimmy      ┆ Male   ┆ 2013-11-19 ┆ 19:29:00      ┆ 63549  ┆ 19.624 ┆ false        ┆ null         │
│ Linda      ┆ Female ┆ 2006-06-24 ┆ 12:04:00      ┆ 110967 ┆ 19.612 ┆ true         ┆ Human        │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Resources    │
│ Joseph     ┆ Male   ┆ 1982-11-04 ┆ 21:46:00      ┆ 126010 ┆ 19.601 ┆ false        ┆ Legal        │
│ Thomas     ┆ Male   ┆ 2016-03-12 ┆ 15:10:00      ┆ 105681 ┆ 19.572 ┆ false        ┆ Engineering  │
│ Betty      ┆ Female ┆ 2002-06-12 ┆ 03:59:00      ┆ 104896 ┆ 19.55  ┆ true         ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Debra      ┆ Female ┆ 1983-03-12 ┆ 12:19:00      ┆ 74911  ┆ 19.513 ┆ false        ┆ Marketing    │
│ Ruby       ┆ Female ┆ 2006-08-13 ┆ 18:27:00      ┆ 48354  ┆ 19.501 ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Terry      ┆ null   ┆ 2016-07-15 ┆ 00:29:00      ┆ 140002 ┆ 19.49  ┆ true         ┆ Marketing    │
│ Judith     ┆ Female ┆ 2004-03-01 ┆ 07:32:00      ┆ 109324 ┆ 19.488 ┆ false        ┆ Distribution │
│ Ryan       ┆ Male   ┆ 1999-04-27 ┆ 03:41:00      ┆ 85858  ┆ 19.475 ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Keith      ┆ Male   ┆ 2003-02-12 ┆ 15:02:00      ┆ 120672 ┆ 19.467 ┆ false        ┆ Legal        │
│ Andrea     ┆ Female ┆ 2010-10-01 ┆ 11:54:00      ┆ 79123  ┆ 19.422 ┆ false        ┆ Distribution │
│ null       ┆ Female ┆ 2007-06-12 ┆ 17:25:00      ┆ 58112  ┆ 19.414 ┆ null         ┆ Marketing    │
│ Amanda     ┆ null   ┆ 1991-08-11 ┆ 14:15:00      ┆ 46665  ┆ 19.391 ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ null       ┆ Female ┆ 2000-08-23 ┆ 16:19:00      ┆ 95866  ┆ 19.388 ┆ null         ┆ Sales        │
│ null       ┆ Male   ┆ 1989-10-20 ┆ 09:37:00      ┆ 88086  ┆ 19.387 ┆ null         ┆ Finance      │
│ Rose       ┆ Female ┆ 2002-07-06 ┆ 15:57:00      ┆ 63494  ┆ 19.385 ┆ true         ┆ Human        │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Resources    │
│ Jessica    ┆ Female ┆ 1995-10-23 ┆ 05:53:00      ┆ 68759  ┆ 19.343 ┆ true         ┆ Finance      │
│ Justin     ┆ Male   ┆ 1986-05-22 ┆ 06:30:00      ┆ 121508 ┆ 19.334 ┆ true         ┆ Finance      │
│ Brenda     ┆ Female ┆ 2015-01-18 ┆ 16:39:00      ┆ 73749  ┆ 19.332 ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ John       ┆ Male   ┆ 1989-12-23 ┆ 07:01:00      ┆ 80740  ┆ 19.305 ┆ false        ┆ Marketing    │
│ Carl       ┆ Male   ┆ 1987-03-30 ┆ 17:59:00      ┆ 75598  ┆ 19.289 ┆ false        ┆ null         │
│ James      ┆ Male   ┆ 1993-01-15 ┆ 17:19:00      ┆ 148985 ┆ 19.28  ┆ false        ┆ Legal        │
│ Jeremy     ┆ Male   ┆ 1994-05-29 ┆ 06:24:00      ┆ 47885  ┆ 19.276 ┆ true         ┆ Human        │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Resources    │
│ Sandra     ┆ Female ┆ 1998-02-07 ┆ 12:39:00      ┆ 132327 ┆ 19.264 ┆ false        ┆ Product      │
│ Robin      ┆ Female ┆ 2012-10-01 ┆ 02:44:00      ┆ 41808  ┆ 19.239 ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Virginia   ┆ Female ┆ 1999-10-20 ┆ 06:23:00      ┆ 46905  ┆ 19.154 ┆ false        ┆ Distribution │
│ Susan      ┆ Female ┆ 1986-04-18 ┆ 09:31:00      ┆ 90829  ┆ 19.142 ┆ false        ┆ Marketing    │
│ Terry      ┆ Male   ┆ 1990-09-03 ┆ 21:15:00      ┆ 52226  ┆ 19.135 ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Amy        ┆ Female ┆ 2009-05-20 ┆ 06:26:00      ┆ 75415  ┆ 19.132 ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Steven     ┆ Male   ┆ 1985-11-10 ┆ 10:53:00      ┆ 62719  ┆ 19.127 ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Philip     ┆ Male   ┆ 1985-07-18 ┆ 06:36:00      ┆ 122319 ┆ 19.122 ┆ false        ┆ Engineering  │
│ …          ┆ …      ┆ …          ┆ …             ┆ …      ┆ …      ┆ …            ┆ …            │
│ Kenneth    ┆ Male   ┆ 2006-05-10 ┆ 08:24:00      ┆ 101914 ┆ 1.905  ┆ true         ┆ Distribution │
│ Donna      ┆ Female ┆ 2010-07-22 ┆ 03:48:00      ┆ 81014  ┆ 1.894  ┆ false        ┆ Product      │
│ Louise     ┆ Female ┆ 2003-05-13 ┆ 09:47:00      ┆ 46666  ┆ 1.886  ┆ true         ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Jeremy     ┆ Male   ┆ 1991-05-19 ┆ 13:40:00      ┆ 131513 ┆ 1.876  ┆ true         ┆ Finance      │
│ Jason      ┆ null   ┆ 2008-03-06 ┆ 01:20:00      ┆ 82873  ┆ 1.869  ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Shirley    ┆ Female ┆ 1981-02-28 ┆ 13:23:00      ┆ 113850 ┆ 1.854  ┆ false        ┆ Marketing    │
│ Todd       ┆ Male   ┆ 2011-05-23 ┆ 16:14:00      ┆ 85074  ┆ 1.844  ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Roy        ┆ Male   ┆ 2006-08-06 ┆ 07:52:00      ┆ 148225 ┆ 1.841  ┆ false        ┆ Finance      │
│ null       ┆ Female ┆ 2005-02-23 ┆ 21:50:00      ┆ 149654 ┆ 1.825  ┆ null         ┆ Sales        │
│ Lisa       ┆ Female ┆ 2009-11-02 ┆ 09:42:00      ┆ 115387 ┆ 1.821  ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Elizabeth  ┆ Female ┆ 2005-11-10 ┆ 04:56:00      ┆ 106406 ┆ 1.782  ┆ true         ┆ Legal        │
│ Katherine  ┆ Female ┆ 1999-11-14 ┆ 08:15:00      ┆ 57531  ┆ 1.767  ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Sarah      ┆ Female ┆ 1980-11-03 ┆ 14:47:00      ┆ 37259  ┆ 1.763  ┆ false        ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Cynthia    ┆ Female ┆ 1994-03-21 ┆ 08:34:00      ┆ 142321 ┆ 1.737  ┆ false        ┆ Finance      │
│ null       ┆ null   ┆ 1988-09-02 ┆ 12:49:00      ┆ 147309 ┆ 1.702  ┆ null         ┆ Distribution │
│ Todd       ┆ Male   ┆ 1990-02-18 ┆ 02:41:00      ┆ 49339  ┆ 1.695  ┆ true         ┆ Human        │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Resources    │
│ Jeremy     ┆ Male   ┆ 2000-06-08 ┆ 00:15:00      ┆ 49542  ┆ 1.679  ┆ true         ┆ Distribution │
│ Joe        ┆ Male   ┆ 2010-12-05 ┆ 16:20:00      ┆ 144082 ┆ 1.62   ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Todd       ┆ Male   ┆ 2009-03-11 ┆ 03:43:00      ┆ 107281 ┆ 1.612  ┆ true         ┆ Engineering  │
│ Virginia   ┆ null   ┆ 1994-05-07 ┆ 17:58:00      ┆ 111858 ┆ 1.601  ┆ true         ┆ Legal        │
│ Howard     ┆ Male   ┆ 1992-04-27 ┆ 01:10:00      ┆ 105062 ┆ 1.563  ┆ false        ┆ Human        │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Resources    │
│ Margaret   ┆ Female ┆ 2001-01-04 ┆ 03:07:00      ┆ 126924 ┆ 1.552  ┆ true         ┆ Finance      │
│ Chris      ┆ Male   ┆ 2006-12-12 ┆ 01:57:00      ┆ 71642  ┆ 1.496  ┆ false        ┆ null         │
│ Theresa    ┆ Female ┆ 2010-04-11 ┆ 07:18:00      ┆ 72670  ┆ 1.481  ┆ true         ┆ Engineering  │
│ Willie     ┆ Male   ┆ 1998-02-17 ┆ 20:20:00      ┆ 146651 ┆ 1.451  ┆ true         ┆ Engineering  │
│ Kathy      ┆ Female ┆ 2001-01-14 ┆ 05:11:00      ┆ 45682  ┆ 1.451  ┆ true         ┆ Marketing    │
│ Amanda     ┆ Female ┆ 1982-03-17 ┆ 23:46:00      ┆ 107111 ┆ 1.438  ┆ true         ┆ Product      │
│ Frances    ┆ Female ┆ 1996-11-12 ┆ 18:08:00      ┆ 112467 ┆ 1.433  ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Henry      ┆ Male   ┆ 1986-05-12 ┆ 02:04:00      ┆ 59943  ┆ 1.432  ┆ false        ┆ Finance      │
│ Kelly      ┆ Female ┆ 1996-08-16 ┆ 03:09:00      ┆ 41427  ┆ 1.431  ┆ false        ┆ Product      │
│ Russell    ┆ Male   ┆ 2013-05-20 ┆ 12:39:00      ┆ 96914  ┆ 1.421  ┆ false        ┆ Product      │
│ null       ┆ Female ┆ 1994-12-18 ┆ 20:42:00      ┆ 138807 ┆ 1.4    ┆ null         ┆ Human        │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Resources    │
│ Larry      ┆ Male   ┆ 1998-01-24 ┆ 16:47:00      ┆ 101004 ┆ 1.389  ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Peter      ┆ Male   ┆ 1992-11-24 ┆ 17:43:00      ┆ 69297  ┆ 1.268  ┆ false        ┆ Finance      │
│ Charles    ┆ Male   ┆ 2004-09-14 ┆ 20:13:00      ┆ 107391 ┆ 1.26   ┆ true         ┆ Marketing    │
│ Lillian    ┆ Female ┆ 2016-06-05 ┆ 06:09:00      ┆ 59414  ┆ 1.256  ┆ false        ┆ Product      │
│ Clarence   ┆ Male   ┆ 1998-05-02 ┆ 03:16:00      ┆ 85700  ┆ 1.215  ┆ false        ┆ Sales        │
│ Steve      ┆ Male   ┆ 2002-01-11 ┆ 21:17:00      ┆ 51821  ┆ 1.197  ┆ true         ┆ Legal        │
│ Harold     ┆ Male   ┆ 2010-10-18 ┆ 20:45:00      ┆ 65673  ┆ 1.187  ┆ true         ┆ Legal        │
│ Joe        ┆ Male   ┆ 1980-01-19 ┆ 16:06:00      ┆ 119667 ┆ 1.148  ┆ true         ┆ Finance      │
│ Ruby       ┆ Female ┆ 2000-11-08 ┆ 19:35:00      ┆ 105946 ┆ 1.139  ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Nicholas   ┆ Male   ┆ 1994-04-12 ┆ 20:21:00      ┆ 74669  ┆ 1.113  ┆ true         ┆ Product      │
│ Gloria     ┆ null   ┆ 1983-07-19 ┆ 01:57:00      ┆ 140885 ┆ 1.113  ┆ false        ┆ Human        │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Resources    │
│ null       ┆ Female ┆ 2013-04-27 ┆ 06:40:00      ┆ 93847  ┆ 1.085  ┆ null         ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Theresa    ┆ Female ┆ 2001-04-27 ┆ 21:17:00      ┆ 75661  ┆ 1.079  ┆ true         ┆ Legal        │
│ Gloria     ┆ Female ┆ 2004-08-19 ┆ 10:31:00      ┆ 46602  ┆ 1.027  ┆ true         ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Helen      ┆ null   ┆ 1993-12-02 ┆ 13:42:00      ┆ 45724  ┆ 1.022  ┆ false        ┆ Product      │
│ Joe        ┆ Male   ┆ 1998-12-08 ┆ 10:28:00      ┆ 126120 ┆ 1.02   ┆ false        ┆ null         │
│ Willie     ┆ Male   ┆ 2009-12-05 ┆ 05:39:00      ┆ 141932 ┆ 1.017  ┆ true         ┆ Engineering  │
│ Douglas    ┆ Male   ┆ 1999-09-03 ┆ 16:00:00      ┆ 83341  ┆ 1.015  ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
└────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘

In [ ]:
## 다중 컬럼 정렬

df.sort(
    by=['Team', 'Salary'],
    descending=[False, True],
    nulls_last=True
    )

shape: (1_000, 8)
┌─────────────┬────────┬────────────┬──────────────┬────────┬────────┬──────────────┬──────────────┐
│ First Name  ┆ Gender ┆ Start Date ┆ Last Login   ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
│ ---         ┆ ---    ┆ ---        ┆ Time         ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
│ str         ┆ str    ┆ date       ┆ ---          ┆ i32    ┆ f64    ┆ ---          ┆ str          │
│             ┆        ┆            ┆ time         ┆        ┆        ┆ bool         ┆              │
╞═════════════╪════════╪════════════╪══════════════╪════════╪════════╪══════════════╪══════════════╡
│ Harold      ┆ Male   ┆ 2010-04-16 ┆ 05:13:00     ┆ 147417 ┆ 11.626 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Marilyn     ┆ Female ┆ 1982-12-17 ┆ 12:10:00     ┆ 147183 ┆ 8.748  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Clarence    ┆ Male   ┆ 1982-08-26 ┆ 09:47:00     ┆ 146589 ┆ 4.905  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Linda       ┆ Female ┆ 2009-07-15 ┆ 22:12:00     ┆ 144001 ┆ 2.194  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Rachel      ┆ Female ┆ 2009-02-16 ┆ 20:47:00     ┆ 142032 ┆ 12.599 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Doris       ┆ Female ┆ 1993-07-05 ┆ 17:54:00     ┆ 141439 ┆ 3.799  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Dorothy     ┆ Female ┆ 2013-11-05 ┆ 22:50:00     ┆ 140136 ┆ 3.12   ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Frances     ┆ Female ┆ 2002-08-08 ┆ 06:51:00     ┆ 139852 ┆ 7.524  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Janice      ┆ null   ┆ 1991-11-19 ┆ 18:02:00     ┆ 139791 ┆ 16.968 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Albert      ┆ Male   ┆ 2008-08-14 ┆ 17:43:00     ┆ 137840 ┆ 9.705  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Russell     ┆ Male   ┆ 2013-05-10 ┆ 23:08:00     ┆ 137359 ┆ 11.105 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ null        ┆ Male   ┆ 2009-06-17 ┆ 13:00:00     ┆ 136681 ┆ 3.655  ┆ null         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Irene       ┆ null   ┆ 1991-02-28 ┆ 22:23:00     ┆ 135369 ┆ 4.38   ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Matthew     ┆ Male   ┆ 1995-08-03 ┆ 05:39:00     ┆ 135352 ┆ 7.986  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Mary        ┆ Female ┆ 1999-08-13 ┆ 01:03:00     ┆ 134645 ┆ 18.197 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Kevin       ┆ Male   ┆ 1981-06-23 ┆ 20:26:00     ┆ 134598 ┆ 11.699 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Kathy       ┆ Female ┆ 2013-12-18 ┆ 15:09:00     ┆ 132381 ┆ 8.34   ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Gregory     ┆ Male   ┆ 1999-11-15 ┆ 17:22:00     ┆ 128031 ┆ 15.857 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Nancy       ┆ Female ┆ 2012-12-15 ┆ 23:57:00     ┆ 125250 ┆ 2.672  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Michelle    ┆ null   ┆ 2012-03-31 ┆ 06:28:00     ┆ 124441 ┆ 16.353 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Clarence    ┆ Male   ┆ 1992-08-20 ┆ 20:23:00     ┆ 124365 ┆ 8.457  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Lillian     ┆ Female ┆ 1999-06-19 ┆ 16:44:00     ┆ 123940 ┆ 12.184 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Mark        ┆ Male   ┆ 1984-04-01 ┆ 13:21:00     ┆ 121477 ┆ 17.44  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Jerry       ┆ Male   ┆ 1995-01-30 ┆ 19:51:00     ┆ 121357 ┆ 18.845 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Brandon     ┆ null   ┆ 1997-11-03 ┆ 20:17:00     ┆ 121333 ┆ 15.295 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Andrea      ┆ Female ┆ 2012-01-12 ┆ 05:43:00     ┆ 120204 ┆ 9.557  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Jean        ┆ Female ┆ 1993-12-18 ┆ 09:07:00     ┆ 119082 ┆ 16.18  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Linda       ┆ Female ┆ 2000-05-25 ┆ 17:45:00     ┆ 119009 ┆ 12.506 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Marilyn     ┆ Female ┆ 1996-01-16 ┆ 07:18:00     ┆ 118369 ┆ 7.696  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Deborah     ┆ Female ┆ 2009-02-26 ┆ 10:17:00     ┆ 118043 ┆ 7.266  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Doris       ┆ Female ┆ 1984-09-08 ┆ 19:03:00     ┆ 114360 ┆ 17.799 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Lillian     ┆ Female ┆ 2009-08-14 ┆ 05:41:00     ┆ 113554 ┆ 18.018 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Frances     ┆ Female ┆ 1996-11-12 ┆ 18:08:00     ┆ 112467 ┆ 1.433  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Jeffrey     ┆ Male   ┆ 1986-09-20 ┆ 06:06:00     ┆ 111376 ┆ 2.673  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Carolyn     ┆ Female ┆ 2011-04-09 ┆ 05:38:00     ┆ 109260 ┆ 2.65   ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Joseph      ┆ Male   ┆ 2010-10-10 ┆ 23:12:00     ┆ 107050 ┆ 12.737 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Denise      ┆ Female ┆ 2001-11-06 ┆ 12:03:00     ┆ 106862 ┆ 3.699  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Ruby        ┆ Female ┆ 2000-11-08 ┆ 19:35:00     ┆ 105946 ┆ 1.139  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Diana       ┆ Female ┆ 2004-11-19 ┆ 08:47:00     ┆ 105066 ┆ 17.343 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Betty       ┆ Female ┆ 2002-06-12 ┆ 03:59:00     ┆ 104896 ┆ 19.55  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Debra       ┆ Female ┆ 1994-02-22 ┆ 22:25:00     ┆ 104250 ┆ 18.456 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Marie       ┆ Female ┆ 2003-03-16 ┆ 00:12:00     ┆ 104058 ┆ 17.695 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Philip      ┆ Male   ┆ 2005-03-11 ┆ 10:56:00     ┆ 103557 ┆ 16.014 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Diana       ┆ Female ┆ 2013-01-04 ┆ 07:53:00     ┆ 103521 ┆ 2.784  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Annie       ┆ null   ┆ 2007-09-29 ┆ 00:11:00     ┆ 103495 ┆ 17.29  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Carl        ┆ null   ┆ 1991-10-26 ┆ 08:11:00     ┆ 100888 ┆ 12.49  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Maria       ┆ Female ┆ 2003-03-14 ┆ 17:23:00     ┆ 96250  ┆ 10.056 ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Mark        ┆ Male   ┆ 1984-10-03 ┆ 05:31:00     ┆ 95728  ┆ 6.752  ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Louis       ┆ Male   ┆ 2011-04-15 ┆ 05:02:00     ┆ 95198  ┆ 2.075  ┆ false        ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ Martha      ┆ Female ┆ 1997-07-17 ┆ 23:11:00     ┆ 94963  ┆ 19.626 ┆ true         ┆ Business     │
│             ┆        ┆            ┆              ┆        ┆        ┆              ┆ Development  │
│ …           ┆ …      ┆ …          ┆ …            ┆ …      ┆ …      ┆ …            ┆ …            │
│ null        ┆ Female ┆ 1991-07-09 ┆ 18:52:00     ┆ 42341  ┆ 7.014  ┆ null         ┆ Sales        │
│ Thomas      ┆ null   ┆ 1995-08-31 ┆ 20:31:00     ┆ 41549  ┆ 3.95   ┆ false        ┆ Sales        │
│ Janice      ┆ Female ┆ 1984-01-02 ┆ 21:06:00     ┆ 41190  ┆ 3.311  ┆ true         ┆ Sales        │
│ null        ┆ null   ┆ 2011-12-17 ┆ 08:29:00     ┆ 41126  ┆ 14.009 ┆ null         ┆ Sales        │
│ Denise      ┆ Female ┆ 2001-03-18 ┆ 00:02:00     ┆ 36697  ┆ 11.196 ┆ true         ┆ Sales        │
│ Frances     ┆ Female ┆ 2014-05-16 ┆ 08:31:00     ┆ 35884  ┆ 17.667 ┆ false        ┆ Sales        │
│ Bruce       ┆ Male   ┆ 1980-05-07 ┆ 20:00:00     ┆ 35802  ┆ 12.391 ┆ true         ┆ Sales        │
│ Charles     ┆ Male   ┆ 1997-09-03 ┆ 10:04:00     ┆ 148291 ┆ 6.002  ┆ false        ┆ null         │
│ Bobby       ┆ Male   ┆ 1996-08-19 ┆ 01:16:00     ┆ 147842 ┆ 16.158 ┆ true         ┆ null         │
│ null        ┆ Female ┆ 2010-09-14 ┆ 05:19:00     ┆ 143638 ┆ 9.662  ┆ null         ┆ null         │
│ Mildred     ┆ Female ┆ 2007-04-06 ┆ 22:06:00     ┆ 139284 ┆ 11.39  ┆ true         ┆ null         │
│ null        ┆ Female ┆ 1990-10-03 ┆ 01:08:00     ┆ 132373 ┆ 10.527 ┆ null         ┆ null         │
│ null        ┆ Female ┆ 1997-04-13 ┆ 08:03:00     ┆ 131755 ┆ 2.93   ┆ null         ┆ null         │
│ Jonathan    ┆ Male   ┆ 2009-07-17 ┆ 08:15:00     ┆ 130581 ┆ 16.736 ┆ true         ┆ null         │
│ Jeremy      ┆ Male   ┆ 1988-06-14 ┆ 18:20:00     ┆ 129460 ┆ 13.657 ┆ true         ┆ null         │
│ James       ┆ null   ┆ 2005-01-26 ┆ 23:00:00     ┆ 128771 ┆ 8.309  ┆ false        ┆ null         │
│ Todd        ┆ Male   ┆ 1993-07-04 ┆ 18:53:00     ┆ 128175 ┆ 18.473 ┆ true         ┆ null         │
│ Joe         ┆ Male   ┆ 1998-12-08 ┆ 10:28:00     ┆ 126120 ┆ 1.02   ┆ false        ┆ null         │
│ null        ┆ Male   ┆ 2012-06-14 ┆ 16:19:00     ┆ 125792 ┆ 5.042  ┆ null         ┆ null         │
│ Donald      ┆ Male   ┆ 1988-04-06 ┆ 10:00:00     ┆ 122920 ┆ 5.32   ┆ false        ┆ null         │
│ null        ┆ Male   ┆ 1998-08-21 ┆ 14:27:00     ┆ 122340 ┆ 6.417  ┆ null         ┆ null         │
│ Alice       ┆ Female ┆ 2016-01-21 ┆ 17:07:00     ┆ 117787 ┆ 10.485 ┆ false        ┆ null         │
│ Bobby       ┆ Male   ┆ 1996-03-31 ┆ 17:40:00     ┆ 112117 ┆ 6.338  ┆ false        ┆ null         │
│ null        ┆ Female ┆ 1996-04-18 ┆ 15:57:00     ┆ 107024 ┆ 12.182 ┆ null         ┆ null         │
│ null        ┆ Female ┆ 2000-06-18 ┆ 07:36:00     ┆ 106428 ┆ 10.867 ┆ null         ┆ null         │
│ Randy       ┆ Male   ┆ 2000-09-27 ┆ 03:04:00     ┆ 89831  ┆ 13.047 ┆ true         ┆ null         │
│ Phillip     ┆ null   ┆ 2003-10-20 ┆ 11:09:00     ┆ 89700  ┆ 2.277  ┆ true         ┆ null         │
│ null        ┆ null   ┆ 1988-08-01 ┆ 01:35:00     ┆ 87103  ┆ 5.665  ┆ null         ┆ null         │
│ Joseph      ┆ null   ┆ 1982-03-28 ┆ 13:05:00     ┆ 86564  ┆ 11.879 ┆ true         ┆ null         │
│ Kimberly    ┆ Female ┆ 1981-12-30 ┆ 04:51:00     ┆ 81800  ┆ 5.435  ┆ true         ┆ null         │
│ Wanda       ┆ Female ┆ 1993-04-06 ┆ 03:11:00     ┆ 78883  ┆ 19.695 ┆ false        ┆ null         │
│ Daniel      ┆ Male   ┆ 2016-02-29 ┆ 04:04:00     ┆ 77287  ┆ 13.0   ┆ true         ┆ null         │
│ Carl        ┆ Male   ┆ 1987-03-30 ┆ 17:59:00     ┆ 75598  ┆ 19.289 ┆ false        ┆ null         │
│ Chris       ┆ Male   ┆ 2006-12-12 ┆ 01:57:00     ┆ 71642  ┆ 1.496  ┆ false        ┆ null         │
│ Jason       ┆ Male   ┆ 1998-11-20 ┆ 14:54:00     ┆ 69244  ┆ 6.22   ┆ true         ┆ null         │
│ Edward      ┆ Male   ┆ 1989-08-04 ┆ 06:06:00     ┆ 66067  ┆ 10.957 ┆ true         ┆ null         │
│ Harry       ┆ Male   ┆ 1985-01-27 ┆ 20:18:00     ┆ 65482  ┆ 18.089 ┆ false        ┆ null         │
│ Jimmy       ┆ Male   ┆ 2013-11-19 ┆ 19:29:00     ┆ 63549  ┆ 19.624 ┆ false        ┆ null         │
│ Louise      ┆ Female ┆ 1980-08-12 ┆ 09:01:00     ┆ 63241  ┆ 15.132 ┆ true         ┆ null         │
│ Thomas      ┆ Male   ┆ 1996-03-31 ┆ 06:53:00     ┆ 61933  ┆ 4.17   ┆ true         ┆ null         │
│ Ryan        ┆ Male   ┆ 2012-11-16 ┆ 13:47:00     ┆ 57292  ┆ 6.01   ┆ false        ┆ null         │
│ Peter       ┆ Male   ┆ 2003-02-22 ┆ 09:09:00     ┆ 56580  ┆ 8.411  ┆ true         ┆ null         │
│ Joyce       ┆ Female ┆ 1995-02-07 ┆ 07:38:00     ┆ 50701  ┆ 14.227 ┆ true         ┆ null         │
│ null        ┆ Female ┆ 1980-04-01 ┆ 20:04:00     ┆ 48141  ┆ 12.605 ┆ null         ┆ null         │
│ Richard     ┆ Male   ┆ 1997-07-04 ┆ 11:47:00     ┆ 47647  ┆ 18.787 ┆ true         ┆ null         │
│ Lawrence    ┆ Male   ┆ 1995-07-03 ┆ 22:55:00     ┆ 46378  ┆ 9.127  ┆ false        ┆ null         │
│ Nicole      ┆ Female ┆ 2004-03-01 ┆ 17:17:00     ┆ 44021  ┆ 10.286 ┆ false        ┆ null         │
│ Michael     ┆ Male   ┆ 2002-01-24 ┆ 03:04:00     ┆ 43586  ┆ 12.659 ┆ false        ┆ null         │
│ Antonio     ┆ Male   ┆ 1999-06-06 ┆ 22:54:00     ┆ 41928  ┆ 5.478  ┆ true         ┆ null         │
│ Christopher ┆ Male   ┆ 2000-04-22 ┆ 10:15:00     ┆ 37919  ┆ 11.449 ┆ false        ┆ null         │
└─────────────┴────────┴────────────┴──────────────┴────────┴────────┴──────────────┴──────────────┘

In [ ]:
df1 = df.head(10).sort("Salary")
df2 = df.tail(10).sort("Salary")

df1, df2

(shape: (10, 8)
 ┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
 │ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
 │ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
 │ str        ┆ str    ┆ date       ┆ ---           ┆ i32    ┆ f64    ┆ ---          ┆ str          │
 │            ┆        ┆            ┆ time          ┆        ┆        ┆ bool         ┆              │
 ╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
 │ null       ┆ Female ┆ 2015-07-20 ┆ 10:43:00      ┆ 45906  ┆ 11.598 ┆ null         ┆ Finance      │
 │ Thomas     ┆ Male   ┆ 1996-03-31 ┆ 06:53:00      ┆ 61933  ┆ 4.17   ┆ true         ┆ null         │
 │ Ruby       ┆ Female ┆ 1987-08-17 ┆ 16:20:00      ┆ 65476  ┆ 10.012 ┆ true         ┆ Product      │
 │ Angela     ┆ Female ┆ 2005-11-22 ┆ 06:29:00      ┆ 95570  ┆ 18.523 ┆ true         ┆ Engineering  │
 │ Douglas    ┆ Male   ┆ 1993-08-06 ┆ 12:42:00      ┆ 97308  ┆ 6.945  ┆ true         ┆ Marketing    │
 │ Larry      ┆ Male   ┆ 1998-01-24 ┆ 16:47:00      ┆ 101004 ┆ 1.389  ┆ true         ┆ Client       │
 │            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
 │ Dennis     ┆ Male   ┆ 1987-04-18 ┆ 01:35:00      ┆ 115163 ┆ 10.125 ┆ false        ┆ Legal        │
 │ Maria      ┆ Female ┆ 1993-04-23 ┆ 11:17:00      ┆ 130590 ┆ 11.858 ┆ false        ┆ Finance      │
 │ Jerry      ┆ Male   ┆ 2005-03-04 ┆ 13:00:00      ┆ 138705 ┆ 9.34   ┆ true         ┆ Finance      │
 │ Frances    ┆ Female ┆ 2002-08-08 ┆ 06:51:00      ┆ 139852 ┆ 7.524  ┆ true         ┆ Business     │
 │            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
 └────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘,
 shape: (10, 8)
 ┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
 │ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
 │ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
 │ str        ┆ str    ┆ date       ┆ ---           ┆ i32    ┆ f64    ┆ ---          ┆ str          │
 │            ┆        ┆            ┆ time          ┆        ┆        ┆ bool         ┆              │
 ╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
 │ Phillip    ┆ Male   ┆ 1984-01-31 ┆ 06:30:00      ┆ 42392  ┆ 19.675 ┆ false        ┆ Finance      │
 │ Tina       ┆ Female ┆ 1997-05-15 ┆ 15:53:00      ┆ 56450  ┆ 19.04  ┆ true         ┆ Engineering  │
 │ Larry      ┆ Male   ┆ 2013-04-20 ┆ 16:45:00      ┆ 60500  ┆ 11.985 ┆ false        ┆ Business     │
 │            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
 │ Russell    ┆ Male   ┆ 2013-05-20 ┆ 12:39:00      ┆ 96914  ┆ 1.421  ┆ false        ┆ Product      │
 │ George     ┆ Male   ┆ 2013-06-21 ┆ 17:47:00      ┆ 98874  ┆ 4.479  ┆ true         ┆ Marketing    │
 │ Robin      ┆ Female ┆ 1987-07-24 ┆ 13:35:00      ┆ 100765 ┆ 10.982 ┆ true         ┆ Client       │
 │            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
 │ Anthony    ┆ Male   ┆ 2011-10-16 ┆ 08:35:00      ┆ 112769 ┆ 11.625 ┆ true         ┆ Finance      │
 │ Albert     ┆ Male   ┆ 2012-05-15 ┆ 18:24:00      ┆ 129949 ┆ 10.169 ┆ true         ┆ Sales        │
 │ Henry      ┆ null   ┆ 2014-11-23 ┆ 06:09:00      ┆ 132483 ┆ 16.655 ┆ false        ┆ Distribution │
 │ Rose       ┆ Female ┆ 2002-08-25 ┆ 05:12:00      ┆ 134505 ┆ 11.051 ┆ true         ┆ Marketing    │
 └────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘)

In [ ]:
"""
두 개의 df 특정 컬럼을 기준으로 정렬하여 merge한다.
단, 기존 df들의 순서를 바꾸지는 않는다.
"""

df1.merge_sorted(df2, 'Salary')

shape: (20, 8)
┌────────────┬────────┬────────────┬───────────────┬────────┬────────┬──────────────┬──────────────┐
│ First Name ┆ Gender ┆ Start Date ┆ Last Login    ┆ Salary ┆ Bonus  ┆ Senior       ┆ Team         │
│ ---        ┆ ---    ┆ ---        ┆ Time          ┆ ---    ┆ ---    ┆ Management   ┆ ---          │
│ str        ┆ str    ┆ date       ┆ ---           ┆ i32    ┆ f64    ┆ ---          ┆ str          │
│            ┆        ┆            ┆ time          ┆        ┆        ┆ bool         ┆              │
╞════════════╪════════╪════════════╪═══════════════╪════════╪════════╪══════════════╪══════════════╡
│ Phillip    ┆ Male   ┆ 1984-01-31 ┆ 06:30:00      ┆ 42392  ┆ 19.675 ┆ false        ┆ Finance      │
│ null       ┆ Female ┆ 2015-07-20 ┆ 10:43:00      ┆ 45906  ┆ 11.598 ┆ null         ┆ Finance      │
│ Tina       ┆ Female ┆ 1997-05-15 ┆ 15:53:00      ┆ 56450  ┆ 19.04  ┆ true         ┆ Engineering  │
│ Larry      ┆ Male   ┆ 2013-04-20 ┆ 16:45:00      ┆ 60500  ┆ 11.985 ┆ false        ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
│ Thomas     ┆ Male   ┆ 1996-03-31 ┆ 06:53:00      ┆ 61933  ┆ 4.17   ┆ true         ┆ null         │
│ Ruby       ┆ Female ┆ 1987-08-17 ┆ 16:20:00      ┆ 65476  ┆ 10.012 ┆ true         ┆ Product      │
│ Angela     ┆ Female ┆ 2005-11-22 ┆ 06:29:00      ┆ 95570  ┆ 18.523 ┆ true         ┆ Engineering  │
│ Russell    ┆ Male   ┆ 2013-05-20 ┆ 12:39:00      ┆ 96914  ┆ 1.421  ┆ false        ┆ Product      │
│ Douglas    ┆ Male   ┆ 1993-08-06 ┆ 12:42:00      ┆ 97308  ┆ 6.945  ┆ true         ┆ Marketing    │
│ George     ┆ Male   ┆ 2013-06-21 ┆ 17:47:00      ┆ 98874  ┆ 4.479  ┆ true         ┆ Marketing    │
│ Robin      ┆ Female ┆ 1987-07-24 ┆ 13:35:00      ┆ 100765 ┆ 10.982 ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Larry      ┆ Male   ┆ 1998-01-24 ┆ 16:47:00      ┆ 101004 ┆ 1.389  ┆ true         ┆ Client       │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Services     │
│ Anthony    ┆ Male   ┆ 2011-10-16 ┆ 08:35:00      ┆ 112769 ┆ 11.625 ┆ true         ┆ Finance      │
│ Dennis     ┆ Male   ┆ 1987-04-18 ┆ 01:35:00      ┆ 115163 ┆ 10.125 ┆ false        ┆ Legal        │
│ Albert     ┆ Male   ┆ 2012-05-15 ┆ 18:24:00      ┆ 129949 ┆ 10.169 ┆ true         ┆ Sales        │
│ Maria      ┆ Female ┆ 1993-04-23 ┆ 11:17:00      ┆ 130590 ┆ 11.858 ┆ false        ┆ Finance      │
│ Henry      ┆ null   ┆ 2014-11-23 ┆ 06:09:00      ┆ 132483 ┆ 16.655 ┆ false        ┆ Distribution │
│ Rose       ┆ Female ┆ 2002-08-25 ┆ 05:12:00      ┆ 134505 ┆ 11.051 ┆ true         ┆ Marketing    │
│ Jerry      ┆ Male   ┆ 2005-03-04 ┆ 13:00:00      ┆ 138705 ┆ 9.34   ┆ true         ┆ Finance      │
│ Frances    ┆ Female ┆ 2002-08-08 ┆ 06:51:00      ┆ 139852 ┆ 7.524  ┆ true         ┆ Business     │
│            ┆        ┆            ┆               ┆        ┆        ┆              ┆ Development  │
└────────────┴────────┴────────────┴───────────────┴────────┴────────┴──────────────┴──────────────┘

## 7. GROUP BY

In [ ]:
# group by

df.group_by('Gender').agg(
    gender_cnt=pl.col('Gender').count()
    )

df.group_by('Gender').agg(
    pl.count('Gender').alias('gender_cnt')
    )

shape: (3, 2)
┌────────┬────────────┐
│ Gender ┆ gender_cnt │
│ ---    ┆ ---        │
│ str    ┆ u32        │
╞════════╪════════════╡
│ Female ┆ 431        │
│ Male   ┆ 424        │
│ null   ┆ 0          │
└────────┴────────────┘

In [ ]:
# group by + sort

df.group_by('Team').agg(
    cnt = pl.count('Team'),
    max_sal = pl.max('Salary'),
    mean_sal = pl.mean('Salary'),
    min_sal = pl.min('Salary'),
    mean_bonus = pl.mean('Bonus'),
    ).sort('mean_sal', descending=True)

shape: (11, 6)
┌──────────────────────┬─────┬─────────┬──────────────┬─────────┬────────────┐
│ Team                 ┆ cnt ┆ max_sal ┆ mean_sal     ┆ min_sal ┆ mean_bonus │
│ ---                  ┆ --- ┆ ---     ┆ ---          ┆ ---     ┆ ---        │
│ str                  ┆ u32 ┆ i32     ┆ f64          ┆ i32     ┆ f64        │
╞══════════════════════╪═════╪═════════╪══════════════╪═════════╪════════════╡
│ Engineering          ┆ 92  ┆ 147362  ┆ 94269.195652 ┆ 36946   ┆ 10.462989  │
│ Finance              ┆ 102 ┆ 149908  ┆ 92219.480392 ┆ 35381   ┆ 10.186873  │
│ Sales                ┆ 94  ┆ 149654  ┆ 92173.43617  ┆ 35802   ┆ 10.116915  │
│ Business Development ┆ 101 ┆ 147417  ┆ 91866.316832 ┆ 36844   ┆ 10.572376  │
│ Human Resources      ┆ 91  ┆ 149903  ┆ 90944.527473 ┆ 35203   ┆ 9.993879   │
│ null                 ┆ 0   ┆ 148291  ┆ 90763.139535 ┆ 37919   ┆ 10.384395  │
│ Marketing            ┆ 98  ┆ 149456  ┆ 90435.591837 ┆ 36643   ┆ 10.353449  │
│ Legal                ┆ 88  ┆ 148985  ┆ 89303.613636 ┆ 35061   ┆ 10.32283   │
│ Product              ┆ 95  ┆ 149684  ┆ 88665.505263 ┆ 35013   ┆ 9.791484   │
│ Distribution         ┆ 90  ┆ 149105  ┆ 88500.466667 ┆ 35575   ┆ 9.615644   │
│ Client Services      ┆ 106 ┆ 147183  ┆ 88224.424528 ┆ 35095   ┆ 10.495104  │
└──────────────────────┴─────┴─────────┴──────────────┴─────────┴────────────┘

In [ ]:
# group_by_dynamic 예제
# 30분 단위로
from datetime import datetime
df = pl.DataFrame(
    {
        "time": pl.datetime_range(
            start=datetime(2021, 12, 16),
            end=datetime(2021, 12, 16, 3),
            interval="30m",
            eager=True,
        ),
        "n": range(7),
    }
)
df

shape: (7, 2)
┌─────────────────────┬─────┐
│ time                ┆ n   │
│ ---                 ┆ --- │
│ datetime[μs]        ┆ i64 │
╞═════════════════════╪═════╡
│ 2021-12-16 00:00:00 ┆ 0   │
│ 2021-12-16 00:30:00 ┆ 1   │
│ 2021-12-16 01:00:00 ┆ 2   │
│ 2021-12-16 01:30:00 ┆ 3   │
│ 2021-12-16 02:00:00 ┆ 4   │
│ 2021-12-16 02:30:00 ┆ 5   │
│ 2021-12-16 03:00:00 ┆ 6   │
└─────────────────────┴─────┘

## 8. JOIN

In [ ]:
tp = pl.read_csv("/content/drive/MyDrive/BigData/polars/trainer_pokemon.csv") # 포켓몬 트레이너
pk = pl.read_csv("/content/drive/MyDrive/BigData/polars/pokemon.csv")         # 포켓몬 캐릭터

tp.columns, pk.columns

(['id',
  'trainer_id',
  'pokemon_id',
  'level',
  'experience_point',
  'current_health',
  'catch_date',
  'catch_datetime',
  'location',
  'status'],
 ['id',
  'kor_name',
  'eng_name',
  'type1',
  'type2',
  'total',
  'hp',
  'attack',
  'defense',
  'special_attack',
  'special_defense',
  'speed',
  'generation',
  'is_legendary'])

In [ ]:
tp = tp.rename({"trainer_id":"tp_id"})
pk = pk.rename({"id":"pk_id"})

tp.columns, pk.columns

(['id',
  'tp_id',
  'pokemon_id',
  'level',
  'experience_point',
  'current_health',
  'catch_date',
  'catch_datetime',
  'location',
  'status'],
 ['pk_id',
  'kor_name',
  'eng_name',
  'type1',
  'type2',
  'total',
  'hp',
  'attack',
  'defense',
  'special_attack',
  'special_defense',
  'speed',
  'generation',
  'is_legendary'])

In [ ]:
tp.join(
    other=pk,
    left_on='tp_id',
    right_on='pk_id',
    how='left' # 'inner', 'left', 'right', 'full', 'semi', 'anti', 'cross'
    ).head()

shape: (5, 23)
┌─────┬───────┬────────────┬───────┬───┬─────────────────┬───────┬────────────┬──────────────┐
│ id  ┆ tp_id ┆ pokemon_id ┆ level ┆ … ┆ special_defense ┆ speed ┆ generation ┆ is_legendary │
│ --- ┆ ---   ┆ ---        ┆ ---   ┆   ┆ ---             ┆ ---   ┆ ---        ┆ ---          │
│ i64 ┆ i64   ┆ i64        ┆ i64   ┆   ┆ i64             ┆ i64   ┆ i64        ┆ bool         │
╞═════╪═══════╪════════════╪═══════╪═══╪═════════════════╪═══════╪════════════╪══════════════╡
│ 1   ┆ 7     ┆ 25         ┆ 42    ┆ … ┆ 64              ┆ 43    ┆ 1          ┆ false        │
│ 2   ┆ 15    ┆ 6          ┆ 56    ┆ … ┆ 80              ┆ 75    ┆ 1          ┆ false        │
│ 3   ┆ 4     ┆ 12         ┆ 21    ┆ … ┆ 50              ┆ 65    ┆ 1          ┆ false        │
│ 4   ┆ 12    ┆ 19         ┆ 39    ┆ … ┆ 80              ┆ 70    ┆ 1          ┆ false        │
│ 5   ┆ 1     ┆ 143        ┆ 70    ┆ … ┆ 65              ┆ 45    ┆ 1          ┆ false        │
└─────┴───────┴────────────┴───────┴───┴─────────────────┴───────┴────────────┴──────────────┘